project_id = "pumdlueqoiyihpkpdjcd"

[functions.transcribe]
verify_jwt = false

[functions.summarise]
verify_jwt = false

[functions.summarise-text]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.lookup-practitioner-invite]
verify_jwt = false

[functions.generate-practitioner-invite]
verify_jwt = true

[functions.claim-practitioner-invite]
verify_jwt = true
